<?php
require_once 'bootstrap.php';$u=require_login();if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit;}csrf_check();$a=$_POST['action']??'';$return=$_POST['return']??($_SERVER['HTTP_REFERER']??'app.php');
try{
 if($a==='complete_mission'){complete_mission($u['sic_id'],(string)$_POST['mission_sic_id']);}
 elseif($a==='event_register'){$e=(string)$_POST['event_sic_id'];$s=sic_id();db()->prepare('INSERT OR IGNORE INTO event_registrations(sic_id,event_sic_id,user_sic_id) VALUES(?,?,?)')->execute([$s,$e,$u['sic_id']]);}
 elseif($a==='academy_enroll'){$c=(string)$_POST['course_sic_id'];db()->prepare('INSERT OR IGNORE INTO academy_enrollments(sic_id,user_sic_id,course_sic_id) VALUES(?,?,?)')->execute([sic_id(),$u['sic_id'],$c]);}
 elseif($a==='academy_lesson_complete'){$lesson=(string)$_POST['lesson_sic_id'];$st=db()->prepare('SELECT al.*,ac.sic_id course_sic FROM academy_lessons al JOIN academy_courses ac ON ac.sic_id=al.course_sic_id WHERE al.sic_id=?');$st->execute([$lesson]);$l=$st->fetch();if($l){db()->prepare('INSERT OR IGNORE INTO academy_enrollments(sic_id,user_sic_id,course_sic_id) VALUES(?,?,?)')->execute([sic_id(),$u['sic_id'],$l['course_sic']]);$en=db()->prepare('SELECT * FROM academy_enrollments WHERE user_sic_id=? AND course_sic_id=?');$en->execute([$u['sic_id'],$l['course_sic']]);$er=$en->fetch();db()->prepare('INSERT OR IGNORE INTO academy_lesson_progress(sic_id,enrollment_sic_id,lesson_sic_id,status,completed_at) VALUES(?,?,?,"COMPLETED",CURRENT_TIMESTAMP)')->execute([sic_id(),$er['sic_id'],$lesson]);drx_post($u['sic_id'],null,(float)$l['drx_reward'],'ACADEMY_LESSON',true,'lesson:'.$u['sic_id'].':'.$lesson,$lesson);$total=(int)db()->query('SELECT COUNT(*) FROM academy_lessons WHERE course_sic_id='.db()->quote($l['course_sic']))->fetchColumn();$doneSt=db()->prepare('SELECT COUNT(*) FROM academy_lesson_progress alp JOIN academy_lessons al ON al.sic_id=alp.lesson_sic_id WHERE alp.enrollment_sic_id=? AND alp.status="COMPLETED"');$doneSt->execute([$er['sic_id']]);$done=(int)$doneSt->fetchColumn();$pct=$total?round($done*100/$total):0;db()->prepare('UPDATE academy_enrollments SET progress_pct=?,status=?,completed_at=CASE WHEN ?=100 THEN CURRENT_TIMESTAMP ELSE completed_at END WHERE sic_id=?')->execute([$pct,$pct===100?'COMPLETED':'ENROLLED',$pct,$er['sic_id']]);if($pct===100){$course=db()->prepare('SELECT * FROM academy_courses WHERE sic_id=?');$course->execute([$l['course_sic']]);$cr=$course->fetch();drx_post($u['sic_id'],null,(float)$cr['drx_reward'],'ACADEMY_COURSE',true,'course:'.$u['sic_id'].':'.$l['course_sic'],$l['course_sic']);issue_certificate($u['sic_id'],'ACADEMY_COMPLETION','Completamento · '.$cr['title'],$l['course_sic'],['course'=>$cr['title'],'completed_at'=>date('c')]);}}}
 elseif($a==='dao_vote'){$p=(string)$_POST['proposal_sic_id'];$ps=db()->prepare('SELECT * FROM dao_proposals WHERE sic_id=? AND status="VOTING"');$ps->execute([$p]);$proposal=$ps->fetch();if(!$proposal||!dao_scope_access($u['sic_id'],$proposal['scope_sic_id']??null))throw new RuntimeException('Voto non autorizzato in questo scope.');$choice=in_array($_POST['choice']??'', ['YES','NO','ABSTAIN'],true)?$_POST['choice']:'ABSTAIN';db()->prepare('INSERT INTO dao_proposal_votes(sic_id,proposal_sic_id,user_sic_id,choice,weight) VALUES(?,?,?,?,1) ON CONFLICT(proposal_sic_id,user_sic_id) DO UPDATE SET choice=excluded.choice,created_at=CURRENT_TIMESTAMP')->execute([sic_id(),$p,$u['sic_id'],$choice]);}
 elseif($a==='quick_checkin'){$date=date('Y-m-d');$m=max(1,min(10,(int)($_POST['mood']??5)));$s=max(0,min(10,(int)($_POST['stress']??5)));$c=max(0,min(10,(int)($_POST['craving']??0)));$sl=max(0,min(10,(int)($_POST['sleep']??7)));$note=trim($_POST['note']??'');db()->prepare('INSERT INTO checkins(sic_id,user_sic_id,checkin_date,mood,stress,craving,sleep,note) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_sic_id,checkin_date) DO UPDATE SET mood=excluded.mood,stress=excluded.stress,craving=excluded.craving,sleep=excluded.sleep,note=excluded.note')->execute([sic_id(),$u['sic_id'],$date,$m,$s,$c,$sl,$note]);drx_post($u['sic_id'],null,5,'CHECKIN',true,'checkin:'.$u['sic_id'].':'.$date,null,['date'=>$date]);$_SESSION['flash']='Check-in registrato con successo! +5 DRX';}
 else throw new RuntimeException('Azione non riconosciuta');
 audit($u['sic_id'],'ACTION_'.$a,null,$_POST);$_SESSION['flash']='Operazione completata.';
}catch(Throwable $e){$_SESSION['flash']='Errore: '.$e->getMessage();}
header('Location: '.$return);