<?php require_once 'bootstrap.php';$u=require_admin();$k=[
'Club mondiali'=>(int)db()->query("SELECT COUNT(*) FROM dependex_world_registry WHERE network_level='LOCAL_CLUB'")->fetchColumn(),
'Nazioni'=>(int)db()->query("SELECT COUNT(DISTINCT country) FROM dependex_world_registry WHERE country<>''")->fetchColumn(),
'Geo da completare'=>(int)db()->query("SELECT COUNT(*) FROM geocode_queue WHERE status='PENDING'")->fetchColumn(),
'Utenti'=>(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn(),
'Eventi'=>(int)db()->query("SELECT COUNT(*) FROM events WHERE status='PUBLISHED'")->fetchColumn(),
'Corsi Academy'=>(int)db()->query("SELECT COUNT(*) FROM academy_courses WHERE status='ACTIVE'")->fetchColumn(),
'Proposte DAO'=>(int)db()->query('SELECT COUNT(*) FROM dao_proposals')->fetchColumn(),
'Documenti'=>(int)db()->query('SELECT COUNT(*) FROM generated_documents')->fetchColumn(),
];$levels=db()->query('SELECT network_level,COUNT(*) n FROM dependex_world_registry GROUP BY network_level ORDER BY network_rank DESC')->fetchAll();$pageTitle='Control Center';require '_header.php';?><section class="section-head"><div><span class="eyebrow">Digital Operating System</span><h1>Control Center</h1><p>Rete mondiale, Club, persone, Hudolin Core, Academy, DAO, tesoreria, documenti e automazioni.</p></div></section><section class="metric-grid"><?php foreach($k as $a=>$v):?><div class="metric"><b><?=number_format($v,0,',','.')?></b><span><?=h($a)?></span></div><?php endforeach;?></section><section class="card"><h2>Gerarchia globale</h2><?php foreach($levels as $l):?><div class="leader-row"><b><?=h(substr($l['network_level'],0,1))?></b><span><?=h($l['network_level'])?></span><em><?=number_format((int)$l['n'],0,',','.')?></em></div><?php endforeach;?></section><section class="menu-list"><a href="hudolin-core.php">📜 Hudolin Core <b>›</b></a><a href="world-club-explorer.php">🌍 World Club Explorer <b>›</b></a><a href="world-network-tree.php">🌳 World Network Tree <b>›</b></a><a href="registry.php">👥 Anagrafe <b>›</b></a><a href="academy.php">🎓 Academy <b>›</b></a><a href="event-builder.php">📅 Event Factory <b>›</b></a><a href="graphic-studio.php">🎨 Graphic Studio <b>›</b></a><a href="documents.php">📄 Document Factory <b>›</b></a><a href="dao.php">🗳 DAO Governance <b>›</b></a><a href="finance.php">💶 Finance OS <b>›</b></a><a href="vault-admin.php">◆ DRX Vault <b>›</b></a><a href="social-admin.php">❤️ Social Impact Admin <b>›</b></a><a href="workflow.php">⚙ Workflow Engine <b>›</b></a><a href="integrations.php">🔌 Integrazioni <b>›</b></a><a href="email-admin.php">✉ Email Machine <b>›</b></a><a href="form-builder.php">🧩 Form Builder <b>›</b></a><a href="acl-admin.php">🔐 ACL & Permessi <b>›</b></a><a href="company-brain.php">🧠 Company Brain <b>›</b></a><a href="ncke-admin.php">🧠 Company Brain / NCKE <b>›</b></a><a href="ai-providers.php">🔑 AI Providers <b>›</b></a></section><?php require '_footer.php';?>