<?php
require_once 'bootstrap.php';$u=require_login();$id=$_GET['id']??$_POST['assessment_sic_id']??'';$st=db()->prepare("SELECT * FROM assessments WHERE sic_id=? AND status='ACTIVE'");$st->execute([$id]);$a=$st->fetch();if(!$a){http_response_code(404);exit('Questionario non trovato');}
if((int)$a['professional_only']===1 && !has_role($u['sic_id'],['SUPERADMIN','PROFESSIONAL','SERVITORE'])){http_response_code(403);exit('Area riservata');}
$cfg=json_decode($a['config_json'],true)?:[];$saved=false;
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$answers=[];$sum=0;$n=0;foreach($cfg['items']??[] as $it){$k=$it['key'];$v=max(1,min(10,(int)($_POST['q'][$k]??0)));if($v){$answers[$k]=$v;$sum+=$v;$n++;}}if($n){$score=round($sum/$n,2);$sic=sic_id();db()->prepare("INSERT INTO assessment_sessions(sic_id,assessment_sic_id,user_sic_id,completed_at,score,interpretation_code,raw_json,visibility) VALUES(?,?,?,CURRENT_TIMESTAMP,?,'TREND_ONLY',?,'PRIVATE')")->execute([$sic,$a['sic_id'],$u['sic_id'],$score,json_encode(['answers'=>$answers,'version'=>1],JSON_UNESCAPED_UNICODE)]);audit($u['sic_id'],'ASSESSMENT_COMPLETE',$sic,['assessment'=>$a['code']]);$saved=true;}}
$hist=db()->prepare("SELECT score,completed_at FROM assessment_sessions WHERE assessment_sic_id=? AND user_sic_id=? AND completed_at IS NOT NULL ORDER BY completed_at DESC LIMIT 8");$hist->execute([$a['sic_id'],$u['sic_id']]);$history=$hist->fetchAll();$pageTitle=$a['title'];require '_header.php';?>
<section class="section-head"><div><span class="eyebrow">Privato · non diagnostico</span><h1><?=h($a['title'])?></h1><p><?=h($cfg['disclaimer']??'Autovalutazione privata.')?></p></div></section>
<?php if($saved):?><div class="success">✓ Check-in salvato nel tuo spazio privato. Nessun DRX viene assegnato in base alle risposte.</div><?php endif;?>
<form method="post" class="card stack"><input type="hidden" name="<?=CSRF_KEY?>" value="<?=h(csrf_token())?>"><input type="hidden" name="assessment_sic_id" value="<?=h($a['sic_id'])?>">
<?php foreach($cfg['items']??[] as $it):?><label><?=h($it['label'])?><input type="range" min="1" max="10" value="5" name="q[<?=h($it['key'])?>]" oninput="this.nextElementSibling.textContent=this.value"><output>5</output></label><?php endforeach;?><button class="btn primary">Salva il check-in</button></form>
<?php if($history):?><section class="card"><h2>Il tuo andamento</h2><div class="rank-road"><?php foreach($history as $h):?><div class="rank-step"><b><?=h(substr($h['completed_at'],0,10))?></b><span><?=h((string)$h['score'])?> / 10</span></div><?php endforeach;?></div><small>I punteggi mostrano soltanto il tuo andamento personale nel tempo.</small></section><?php endif;?><?php require '_footer.php';?>
