<?php
require_once 'bootstrap.php';$u=require_login();header('Content-Type: application/json; charset=utf-8');if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['ok'=>false]);exit;}$raw=json_decode(file_get_contents('php://input'),true)?:$_POST;$q=trim((string)($raw['q']??''));if($q===''||mb_strlen($q)>1000){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'invalid_question']);exit;}$bucket='cortex:'.$u['sic_id'];if(!rate_limit($bucket,30,60)){http_response_code(429);echo json_encode(['ok'=>false,'error'=>'rate_limit']);exit;}
$conv=(string)($raw['conversation_sic_id']??'');if($conv===''){$conv=sic_id();db()->prepare('INSERT INTO chat_conversations(sic_id,user_sic_id,title) VALUES(?,?,?)')->execute([$conv,$u['sic_id'],mb_substr($q,0,80)]);}else{$st=db()->prepare('SELECT 1 FROM chat_conversations WHERE sic_id=? AND user_sic_id=?');$st->execute([$conv,$u['sic_id']]);if(!$st->fetchColumn()){http_response_code(403);echo json_encode(['ok'=>false]);exit;}}
db()->prepare('INSERT INTO chat_messages(sic_id,conversation_sic_id,user_sic_id,role,content,privacy_scope) VALUES(?,?,?,?,?,"PRIVATE")')->execute([sic_id(),$conv,$u['sic_id'],'user',$q]);
$answer='';$sources=[];$grounded=false;
try{require_once __DIR__.'/modules/cortex/CortexService.php';$cx=new \Dependex\Cortex\CortexService();$taskLower=mb_strtolower($q);if(preg_match('/(impronta|contesto|identit|valori|mappa|automazion|tesoro|ingranagg|skill|articol|preventiv|quota|report|metric|web3|blockchain|wallet)/u',$taskLower)){$cr=$cx->processMessage($q,$u['sic_id']);if(!empty($cr['message'])){$answer=$cr['message'];$grounded=true;$sources[]=['title'=>'CORTEX Agent: '.($cr['agent']??'core'),'path'=>'cortex/agents'];}}}catch(Throwable $e){}
if(!$answer){try{require_once __DIR__.'/modules/dependex-host-bridge.php';require_once __DIR__.'/modules/neuralog/brain.php';if(brain_has_table(brain_t('nodes'))){$rows=brain_retrieve($q,['admin'=>false,'n'=>5,'neighbors'=>true]);if($rows){$grounded=true;$chunks=[];foreach(array_slice($rows,0,3) as $r){$txt=trim(preg_replace('/\s+/u',' ',(string)$r['content']));if($txt!=='')$chunks[]=mb_substr($txt,0,520);$sources[]=['title'=>$r['title']?:$r['path'],'path'=>$r['path'],'id'=>$r['id']];}$answer="Dalla conoscenza verificata che ho disponibile:\n\n".implode("\n\n",$chunks);}}}catch(Throwable $e){}}
if(!$answer){$term='%'.$q.'%';$st=db()->prepare('SELECT entity_name,city,region,country,address,meeting,public_contact,source_url FROM dependex_world_registry WHERE entity_name LIKE ? OR city LIKE ? OR country LIKE ? LIMIT 5');$st->execute([$term,$term,$term]);$hits=$st->fetchAll();if($hits){$grounded=true;$parts=[];foreach($hits as $h){$parts[]=$h['entity_name'].' — '.implode(' · ',array_filter([$h['city'],$h['region'],$h['country']])).($h['address']?' — '.$h['address']:'');$sources[]=['title'=>$h['entity_name'],'path'=>$h['source_url']];}$answer="Ho trovato questi nodi nella rete DEPENDEX:\n\n".implode("\n",$parts);}else{$answer='Non ho ancora una risposta sufficientemente ancorata nella conoscenza disponibile. Posso comunque aiutarti a trovare Club, eventi, Academy e strumenti dell’app, oppure la domanda può essere inviata alla coda di conoscenza per revisione.';}}
$dbsrc=json_encode($sources,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);db()->prepare('INSERT INTO chat_messages(sic_id,conversation_sic_id,user_sic_id,role,content,grounded,sources_json,privacy_scope) VALUES(?,?,?,?,?,?,?,"PRIVATE")')->execute([sic_id(),$conv,$u['sic_id'],'assistant',$answer,$grounded?1:0,$dbsrc]);db()->prepare('UPDATE chat_conversations SET updated_at=CURRENT_TIMESTAMP WHERE sic_id=?')->execute([$conv]);
// only de-identified/aggregated knowledge gap metric
if(!$grounded){db()->prepare('INSERT INTO community_insights(sic_id,insight_type,period,metric_key,metric_value,dimensions_json) VALUES(?,"KNOWLEDGE_GAP",strftime("%Y-%m"),"unanswered_question",1,?)')->execute([sic_id(),json_encode(['terms'=>array_slice(preg_split('/\s+/u',mb_strtolower($q)),0,5)],JSON_UNESCAPED_UNICODE)]);}
echo json_encode(['ok'=>true,'conversation_sic_id'=>$conv,'answer'=>$answer,'grounded'=>$grounded,'sources'=>$sources],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);